// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLConsoleML.Model
{
    public class ModelInput
    {
        [ColumnName("Id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("Symbol"), LoadColumn(1)]
        public string Symbol { get; set; }


        [ColumnName("TimeInterval"), LoadColumn(2)]
        public string TimeInterval { get; set; }


        [ColumnName("OpenTime"), LoadColumn(3)]
        public float OpenTime { get; set; }


        [ColumnName("Open"), LoadColumn(4)]
        public string Open { get; set; }


        [ColumnName("High"), LoadColumn(5)]
        public string High { get; set; }


        [ColumnName("Low"), LoadColumn(6)]
        public string Low { get; set; }


        [ColumnName("Close"), LoadColumn(7)]
        public string Close { get; set; }


        [ColumnName("Volume"), LoadColumn(8)]
        public string Volume { get; set; }


        [ColumnName("CloseTime"), LoadColumn(9)]
        public float CloseTime { get; set; }


        [ColumnName("QuoteAssetVolume"), LoadColumn(10)]
        public string QuoteAssetVolume { get; set; }


        [ColumnName("NumberOfTrades"), LoadColumn(11)]
        public float NumberOfTrades { get; set; }


        [ColumnName("TakerBuyBaseAssetVolume"), LoadColumn(12)]
        public string TakerBuyBaseAssetVolume { get; set; }


        [ColumnName("TakerBuyQuoteAssetVolume"), LoadColumn(13)]
        public string TakerBuyQuoteAssetVolume { get; set; }


        [ColumnName("Advice"), LoadColumn(14)]
        public float Advice { get; set; }


        [ColumnName("VectorSMA"), LoadColumn(15)]
        public string VectorSMA { get; set; }


    }
}
