//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StaffTimeDbContainer : DbContext
    {
        string passAdmin = ";password=~fy0qL0hyU";
        string passUser = ";password=uBpw9$aW9I";

        public StaffTimeDbContainer()
            : base("name=StaffTimeDbContainer")
        {
            var connectionString = Database.Connection.ConnectionString;
            if (!connectionString.Contains("password="))
            {
                if(connectionString.Contains("staff_admin"))
                    Database.Connection.ConnectionString = connectionString.Trim(';') + passAdmin;
                else if (connectionString.Contains("staff_user"))
                    Database.Connection.ConnectionString = connectionString.Trim(';') + passUser;
            }
                
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<Property> PropertySet { get; set; }
        public virtual DbSet<ActiveProjectOnStaff> ActiveProjectOnStaffSet { get; set; }
    }
}
