//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class Patient : object
    {
        
        private System.DateTime BirthDateField;
        
        private string EmailField;
        
        private string GenderField;
        
        private string NameField;
        
        private string PatronymicField;
        
        private string PhoneField;
        
        private string PolicyNumberField;
        
        private string PolicySeriesField;
        
        private string SnilsField;
        
        private string SurnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patronymic
        {
            get
            {
                return this.PatronymicField;
            }
            set
            {
                this.PatronymicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicySeries
        {
            get
            {
                return this.PolicySeriesField;
            }
            set
            {
                this.PolicySeriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Snils
        {
            get
            {
                return this.SnilsField;
            }
            set
            {
                this.SnilsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MethodResult", Namespace="http://schemas.datacontract.org/2004/07/HubService2")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExamServiceReference.MedicalExaminationQuestioningResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExamServiceReference.GetMedicalServiceAvailableSlotsResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExamServiceReference.GetMedicalExaminationPlanResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExamServiceReference.BookMedicalServiceResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExamServiceReference.CancelMedicalServiceBookingResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExamServiceReference.UpdateMedicalServiceBookingResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExamServiceReference.GetMedicalExaminationQuestionnairesResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExamServiceReference.ValidateMedicalExaminationResult))]
    public partial class MethodResult : object
    {
        
        private System.Collections.Generic.List<ExamServiceReference.Error> ErrorListField;
        
        private System.Nullable<int> IdHistoryField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ExamServiceReference.Error> ErrorList
        {
            get
            {
                return this.ErrorListField;
            }
            set
            {
                this.ErrorListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdHistory
        {
            get
            {
                return this.IdHistoryField;
            }
            set
            {
                this.IdHistoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicalExaminationQuestioningResult", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class MedicalExaminationQuestioningResult : ExamServiceReference.MethodResult
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMedicalServiceAvailableSlotsResult", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class GetMedicalServiceAvailableSlotsResult : ExamServiceReference.MethodResult
    {
        
        private System.Collections.Generic.List<ExamServiceReference.Slot> ListSlotField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ExamServiceReference.Slot> ListSlot
        {
            get
            {
                return this.ListSlotField;
            }
            set
            {
                this.ListSlotField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMedicalExaminationPlanResult", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class GetMedicalExaminationPlanResult : ExamServiceReference.MethodResult
    {
        
        private ExamServiceReference.MedicalExamination MedicalExaminationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamServiceReference.MedicalExamination MedicalExamination
        {
            get
            {
                return this.MedicalExaminationField;
            }
            set
            {
                this.MedicalExaminationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookMedicalServiceResult", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class BookMedicalServiceResult : ExamServiceReference.MethodResult
    {
        
        private ExamServiceReference.MedicalService MedicalServiceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamServiceReference.MedicalService MedicalService
        {
            get
            {
                return this.MedicalServiceField;
            }
            set
            {
                this.MedicalServiceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelMedicalServiceBookingResult", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class CancelMedicalServiceBookingResult : ExamServiceReference.MethodResult
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateMedicalServiceBookingResult", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class UpdateMedicalServiceBookingResult : ExamServiceReference.MethodResult
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMedicalExaminationQuestionnairesResult", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class GetMedicalExaminationQuestionnairesResult : ExamServiceReference.MethodResult
    {
        
        private System.Collections.Generic.List<ExamServiceReference.Questionnaire> ListQuestionnaireField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ExamServiceReference.Questionnaire> ListQuestionnaire
        {
            get
            {
                return this.ListQuestionnaireField;
            }
            set
            {
                this.ListQuestionnaireField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateMedicalExaminationResult", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class ValidateMedicalExaminationResult : ExamServiceReference.MethodResult
    {
        
        private string IdPatField;
        
        private System.Collections.Generic.List<ExamServiceReference.MedicalExamination> ListMedicalExaminationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPat
        {
            get
            {
                return this.IdPatField;
            }
            set
            {
                this.IdPatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ExamServiceReference.MedicalExamination> ListMedicalExamination
        {
            get
            {
                return this.ListMedicalExaminationField;
            }
            set
            {
                this.ListMedicalExaminationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/HubService2")]
    public partial class Error : object
    {
        
        private string ErrorDescriptionField;
        
        private int IdErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription
        {
            get
            {
                return this.ErrorDescriptionField;
            }
            set
            {
                this.ErrorDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdError
        {
            get
            {
                return this.IdErrorField;
            }
            set
            {
                this.IdErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicalExamination", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class MedicalExamination : object
    {
        
        private string ExaminationStatusField;
        
        private string ExaminationStatusNotesField;
        
        private System.Guid IdMedicalExaminationField;
        
        private System.Nullable<bool> IsQuestionnaireFilledField;
        
        private System.Collections.Generic.List<ExamServiceReference.MedicalService> ListMedicalServiceField;
        
        private string MedicalExaminationTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExaminationStatus
        {
            get
            {
                return this.ExaminationStatusField;
            }
            set
            {
                this.ExaminationStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExaminationStatusNotes
        {
            get
            {
                return this.ExaminationStatusNotesField;
            }
            set
            {
                this.ExaminationStatusNotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdMedicalExamination
        {
            get
            {
                return this.IdMedicalExaminationField;
            }
            set
            {
                this.IdMedicalExaminationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsQuestionnaireFilled
        {
            get
            {
                return this.IsQuestionnaireFilledField;
            }
            set
            {
                this.IsQuestionnaireFilledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ExamServiceReference.MedicalService> ListMedicalService
        {
            get
            {
                return this.ListMedicalServiceField;
            }
            set
            {
                this.ListMedicalServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalExaminationType
        {
            get
            {
                return this.MedicalExaminationTypeField;
            }
            set
            {
                this.MedicalExaminationTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Slot", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class Slot : object
    {
        
        private string AddressField;
        
        private System.Guid IdSlotField;
        
        private string RoomField;
        
        private System.DateTime VisitEndField;
        
        private System.DateTime VisitStartField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdSlot
        {
            get
            {
                return this.IdSlotField;
            }
            set
            {
                this.IdSlotField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Room
        {
            get
            {
                return this.RoomField;
            }
            set
            {
                this.RoomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VisitEnd
        {
            get
            {
                return this.VisitEndField;
            }
            set
            {
                this.VisitEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VisitStart
        {
            get
            {
                return this.VisitStartField;
            }
            set
            {
                this.VisitStartField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicalService", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class MedicalService : object
    {
        
        private System.Guid IdMedicalServiceField;
        
        private ExamServiceReference.MedicalServiceAvailableResource MedicalServiceAvailableResourceField;
        
        private ExamServiceReference.MedicalServiceBooking MedicalServiceBookingField;
        
        private string MedicalServiceCodeField;
        
        private string MedicalServiceCommentField;
        
        private string MedicalServiceConditionsField;
        
        private string MedicalServiceNameField;
        
        private bool MedicalServiceRequiredField;
        
        private string MedicalServiceStatusField;
        
        private string MedicalServiceUnavailableReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdMedicalService
        {
            get
            {
                return this.IdMedicalServiceField;
            }
            set
            {
                this.IdMedicalServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamServiceReference.MedicalServiceAvailableResource MedicalServiceAvailableResource
        {
            get
            {
                return this.MedicalServiceAvailableResourceField;
            }
            set
            {
                this.MedicalServiceAvailableResourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamServiceReference.MedicalServiceBooking MedicalServiceBooking
        {
            get
            {
                return this.MedicalServiceBookingField;
            }
            set
            {
                this.MedicalServiceBookingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalServiceCode
        {
            get
            {
                return this.MedicalServiceCodeField;
            }
            set
            {
                this.MedicalServiceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalServiceComment
        {
            get
            {
                return this.MedicalServiceCommentField;
            }
            set
            {
                this.MedicalServiceCommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalServiceConditions
        {
            get
            {
                return this.MedicalServiceConditionsField;
            }
            set
            {
                this.MedicalServiceConditionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalServiceName
        {
            get
            {
                return this.MedicalServiceNameField;
            }
            set
            {
                this.MedicalServiceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MedicalServiceRequired
        {
            get
            {
                return this.MedicalServiceRequiredField;
            }
            set
            {
                this.MedicalServiceRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalServiceStatus
        {
            get
            {
                return this.MedicalServiceStatusField;
            }
            set
            {
                this.MedicalServiceStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalServiceUnavailableReason
        {
            get
            {
                return this.MedicalServiceUnavailableReasonField;
            }
            set
            {
                this.MedicalServiceUnavailableReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicalServiceAvailableResource", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class MedicalServiceAvailableResource : object
    {
        
        private string IdLpuField;
        
        private System.Collections.Generic.List<ExamServiceReference.MedicalResource2> ListMedicalResourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdLpu
        {
            get
            {
                return this.IdLpuField;
            }
            set
            {
                this.IdLpuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ExamServiceReference.MedicalResource2> ListMedicalResource
        {
            get
            {
                return this.ListMedicalResourceField;
            }
            set
            {
                this.ListMedicalResourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicalServiceBooking", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class MedicalServiceBooking : object
    {
        
        private System.Guid BookingMemberField;
        
        private string BookingSourceField;
        
        private System.Guid ChangeBookingMemberField;
        
        private string ChangeBookingSourceField;
        
        private string IdLpuField;
        
        private System.Guid IdMedicalServiceBookingField;
        
        private System.Collections.Generic.List<ExamServiceReference.MedicalResource> ListMedicalResourceField;
        
        private System.DateTime MedicalServiceBookingDateTimeField;
        
        private string MedicalServiceBookingStatusField;
        
        private string MedicalServiceBoookingCommentField;
        
        private string RoomField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BookingMember
        {
            get
            {
                return this.BookingMemberField;
            }
            set
            {
                this.BookingMemberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingSource
        {
            get
            {
                return this.BookingSourceField;
            }
            set
            {
                this.BookingSourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ChangeBookingMember
        {
            get
            {
                return this.ChangeBookingMemberField;
            }
            set
            {
                this.ChangeBookingMemberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChangeBookingSource
        {
            get
            {
                return this.ChangeBookingSourceField;
            }
            set
            {
                this.ChangeBookingSourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdLpu
        {
            get
            {
                return this.IdLpuField;
            }
            set
            {
                this.IdLpuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdMedicalServiceBooking
        {
            get
            {
                return this.IdMedicalServiceBookingField;
            }
            set
            {
                this.IdMedicalServiceBookingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ExamServiceReference.MedicalResource> ListMedicalResource
        {
            get
            {
                return this.ListMedicalResourceField;
            }
            set
            {
                this.ListMedicalResourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MedicalServiceBookingDateTime
        {
            get
            {
                return this.MedicalServiceBookingDateTimeField;
            }
            set
            {
                this.MedicalServiceBookingDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalServiceBookingStatus
        {
            get
            {
                return this.MedicalServiceBookingStatusField;
            }
            set
            {
                this.MedicalServiceBookingStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalServiceBoookingComment
        {
            get
            {
                return this.MedicalServiceBoookingCommentField;
            }
            set
            {
                this.MedicalServiceBoookingCommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Room
        {
            get
            {
                return this.RoomField;
            }
            set
            {
                this.RoomField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicalResource2", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class MedicalResource2 : ExamServiceReference.MedicalResource
    {
        
        private System.Collections.Generic.List<ExamServiceReference.Slot> ListSlotField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ExamServiceReference.Slot> ListSlot
        {
            get
            {
                return this.ListSlotField;
            }
            set
            {
                this.ListSlotField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicalResource", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExamServiceReference.MedicalResource2))]
    public partial class MedicalResource : object
    {
        
        private System.Guid IdMedicalResourceField;
        
        private ExamServiceReference.MedicalEmployee MedicalEmployeeField;
        
        private string MedicalResourceCommentField;
        
        private string MedicalResourceNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdMedicalResource
        {
            get
            {
                return this.IdMedicalResourceField;
            }
            set
            {
                this.IdMedicalResourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamServiceReference.MedicalEmployee MedicalEmployee
        {
            get
            {
                return this.MedicalEmployeeField;
            }
            set
            {
                this.MedicalEmployeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalResourceComment
        {
            get
            {
                return this.MedicalResourceCommentField;
            }
            set
            {
                this.MedicalResourceCommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalResourceName
        {
            get
            {
                return this.MedicalResourceNameField;
            }
            set
            {
                this.MedicalResourceNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicalEmployee", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class MedicalEmployee : object
    {
        
        private string MedicalEmployeeCommentField;
        
        private string MedicalEmployeeFedIdSpecialityField;
        
        private string MedicalEmployeeIdSpecialityField;
        
        private string MedicalEmployeeNameSpecialityField;
        
        private string MedicalEmployeePositionCodeField;
        
        private string MedicalEmployeeSnilsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalEmployeeComment
        {
            get
            {
                return this.MedicalEmployeeCommentField;
            }
            set
            {
                this.MedicalEmployeeCommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalEmployeeFedIdSpeciality
        {
            get
            {
                return this.MedicalEmployeeFedIdSpecialityField;
            }
            set
            {
                this.MedicalEmployeeFedIdSpecialityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalEmployeeIdSpeciality
        {
            get
            {
                return this.MedicalEmployeeIdSpecialityField;
            }
            set
            {
                this.MedicalEmployeeIdSpecialityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalEmployeeNameSpeciality
        {
            get
            {
                return this.MedicalEmployeeNameSpecialityField;
            }
            set
            {
                this.MedicalEmployeeNameSpecialityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalEmployeePositionCode
        {
            get
            {
                return this.MedicalEmployeePositionCodeField;
            }
            set
            {
                this.MedicalEmployeePositionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalEmployeeSnils
        {
            get
            {
                return this.MedicalEmployeeSnilsField;
            }
            set
            {
                this.MedicalEmployeeSnilsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Questionnaire", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class Questionnaire : object
    {
        
        private string CommentField;
        
        private System.Collections.Generic.List<ExamServiceReference.QuestionnaireAnswer> ListQuestionnaireAnswerField;
        
        private string QuestionnaireTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ExamServiceReference.QuestionnaireAnswer> ListQuestionnaireAnswer
        {
            get
            {
                return this.ListQuestionnaireAnswerField;
            }
            set
            {
                this.ListQuestionnaireAnswerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionnaireType
        {
            get
            {
                return this.QuestionnaireTypeField;
            }
            set
            {
                this.QuestionnaireTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionnaireAnswer", Namespace="http://schemas.datacontract.org/2004/07/HubService2.ContractsClasses.Examination")]
    public partial class QuestionnaireAnswer : object
    {
        
        private string AnswerValueField;
        
        private string CommentField;
        
        private string QuestionCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnswerValue
        {
            get
            {
                return this.AnswerValueField;
            }
            set
            {
                this.AnswerValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionCode
        {
            get
            {
                return this.QuestionCodeField;
            }
            set
            {
                this.QuestionCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExamServiceReference.IExaminationService")]
    public interface IExaminationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExaminationService/ValidateMedicalExamination", ReplyAction="http://tempuri.org/IExaminationService/ValidateMedicalExaminationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IExaminationService/ValidateMedicalExaminationFaultExceptionFa" +
            "ult", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        System.Threading.Tasks.Task<ExamServiceReference.ValidateMedicalExaminationResult> ValidateMedicalExaminationAsync(string idLpu, string comment, string medicalExaminationType, System.Guid guid, ExamServiceReference.Patient examinationPatient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExaminationService/MedicalExaminationQuestioning", ReplyAction="http://tempuri.org/IExaminationService/MedicalExaminationQuestioningResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IExaminationService/MedicalExaminationQuestioningFaultExceptio" +
            "nFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        System.Threading.Tasks.Task<ExamServiceReference.MedicalExaminationQuestioningResult> MedicalExaminationQuestioningAsync(string idLpu, string idPat, System.Guid idMedicalExamination, string comment, System.Guid guid, System.Collections.Generic.List<ExamServiceReference.Questionnaire> ListQuestionnaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExaminationService/GetMedicalServiceAvailableSlots", ReplyAction="http://tempuri.org/IExaminationService/GetMedicalServiceAvailableSlotsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IExaminationService/GetMedicalServiceAvailableSlotsFaultExcept" +
            "ionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        System.Threading.Tasks.Task<ExamServiceReference.GetMedicalServiceAvailableSlotsResult> GetMedicalServiceAvailableSlotsAsync(string idLpu, string idPat, System.Guid idMedicalExamination, System.Guid idMedicalService, System.Guid idMedicalResource, System.DateTime slotSearchStartDate, System.DateTime slotSearchEndDate, System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExaminationService/GetMedicalExaminationPlan", ReplyAction="http://tempuri.org/IExaminationService/GetMedicalExaminationPlanResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IExaminationService/GetMedicalExaminationPlanFaultExceptionFau" +
            "lt", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        System.Threading.Tasks.Task<ExamServiceReference.GetMedicalExaminationPlanResult> GetMedicalExaminationPlanAsync(string idLpu, string idPat, System.Guid idMedicalExamination, System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExaminationService/BookMedicalService", ReplyAction="http://tempuri.org/IExaminationService/BookMedicalServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IExaminationService/BookMedicalServiceFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        System.Threading.Tasks.Task<ExamServiceReference.BookMedicalServiceResult> BookMedicalServiceAsync(string idLpu, string idPat, System.Guid idMedicalExamination, System.Guid idMedicalService, System.Guid idMedicalResource, System.Guid idSlot, System.Nullable<System.DateTime> visitStart, System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExaminationService/CancelMedicalServiceBooking", ReplyAction="http://tempuri.org/IExaminationService/CancelMedicalServiceBookingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IExaminationService/CancelMedicalServiceBookingFaultExceptionF" +
            "ault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        System.Threading.Tasks.Task<ExamServiceReference.CancelMedicalServiceBookingResult> CancelMedicalServiceBookingAsync(string idLpu, System.Guid idMedicalServiceBooking, string idPat, System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExaminationService/UpdateMedicalServiceBooking", ReplyAction="http://tempuri.org/IExaminationService/UpdateMedicalServiceBookingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IExaminationService/UpdateMedicalServiceBookingFaultExceptionF" +
            "ault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        System.Threading.Tasks.Task<ExamServiceReference.UpdateMedicalServiceBookingResult> UpdateMedicalServiceBookingAsync(string idLpu, string idPat, System.Guid guid, ExamServiceReference.MedicalExamination medicalExamination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExaminationService/GetMedicalExaminationQuestionnaires", ReplyAction="http://tempuri.org/IExaminationService/GetMedicalExaminationQuestionnairesRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IExaminationService/GetMedicalExaminationQuestionnairesFaultEx" +
            "ceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        System.Threading.Tasks.Task<ExamServiceReference.GetMedicalExaminationQuestionnairesResult> GetMedicalExaminationQuestionnairesAsync(string idLpu, string idPat, System.Guid idMedicalExamination, System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExaminationService/GetVersion", ReplyAction="http://tempuri.org/IExaminationService/GetVersionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IExaminationService/GetVersionFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        System.Threading.Tasks.Task<string> GetVersionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IExaminationServiceChannel : ExamServiceReference.IExaminationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ExaminationServiceClient : System.ServiceModel.ClientBase<ExamServiceReference.IExaminationService>, ExamServiceReference.IExaminationService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ExaminationServiceClient() : 
                base(ExaminationServiceClient.GetDefaultBinding(), ExaminationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IExaminationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExaminationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ExaminationServiceClient.GetBindingForEndpoint(endpointConfiguration), ExaminationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExaminationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ExaminationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExaminationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ExaminationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExaminationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ExamServiceReference.ValidateMedicalExaminationResult> ValidateMedicalExaminationAsync(string idLpu, string comment, string medicalExaminationType, System.Guid guid, ExamServiceReference.Patient examinationPatient)
        {
            return base.Channel.ValidateMedicalExaminationAsync(idLpu, comment, medicalExaminationType, guid, examinationPatient);
        }
        
        public System.Threading.Tasks.Task<ExamServiceReference.MedicalExaminationQuestioningResult> MedicalExaminationQuestioningAsync(string idLpu, string idPat, System.Guid idMedicalExamination, string comment, System.Guid guid, System.Collections.Generic.List<ExamServiceReference.Questionnaire> ListQuestionnaire)
        {
            return base.Channel.MedicalExaminationQuestioningAsync(idLpu, idPat, idMedicalExamination, comment, guid, ListQuestionnaire);
        }
        
        public System.Threading.Tasks.Task<ExamServiceReference.GetMedicalServiceAvailableSlotsResult> GetMedicalServiceAvailableSlotsAsync(string idLpu, string idPat, System.Guid idMedicalExamination, System.Guid idMedicalService, System.Guid idMedicalResource, System.DateTime slotSearchStartDate, System.DateTime slotSearchEndDate, System.Guid guid)
        {
            return base.Channel.GetMedicalServiceAvailableSlotsAsync(idLpu, idPat, idMedicalExamination, idMedicalService, idMedicalResource, slotSearchStartDate, slotSearchEndDate, guid);
        }
        
        public System.Threading.Tasks.Task<ExamServiceReference.GetMedicalExaminationPlanResult> GetMedicalExaminationPlanAsync(string idLpu, string idPat, System.Guid idMedicalExamination, System.Guid guid)
        {
            return base.Channel.GetMedicalExaminationPlanAsync(idLpu, idPat, idMedicalExamination, guid);
        }
        
        public System.Threading.Tasks.Task<ExamServiceReference.BookMedicalServiceResult> BookMedicalServiceAsync(string idLpu, string idPat, System.Guid idMedicalExamination, System.Guid idMedicalService, System.Guid idMedicalResource, System.Guid idSlot, System.Nullable<System.DateTime> visitStart, System.Guid guid)
        {
            return base.Channel.BookMedicalServiceAsync(idLpu, idPat, idMedicalExamination, idMedicalService, idMedicalResource, idSlot, visitStart, guid);
        }
        
        public System.Threading.Tasks.Task<ExamServiceReference.CancelMedicalServiceBookingResult> CancelMedicalServiceBookingAsync(string idLpu, System.Guid idMedicalServiceBooking, string idPat, System.Guid guid)
        {
            return base.Channel.CancelMedicalServiceBookingAsync(idLpu, idMedicalServiceBooking, idPat, guid);
        }
        
        public System.Threading.Tasks.Task<ExamServiceReference.UpdateMedicalServiceBookingResult> UpdateMedicalServiceBookingAsync(string idLpu, string idPat, System.Guid guid, ExamServiceReference.MedicalExamination medicalExamination)
        {
            return base.Channel.UpdateMedicalServiceBookingAsync(idLpu, idPat, guid, medicalExamination);
        }
        
        public System.Threading.Tasks.Task<ExamServiceReference.GetMedicalExaminationQuestionnairesResult> GetMedicalExaminationQuestionnairesAsync(string idLpu, string idPat, System.Guid idMedicalExamination, System.Guid guid)
        {
            return base.Channel.GetMedicalExaminationQuestionnairesAsync(idLpu, idPat, idMedicalExamination, guid);
        }
        
        public System.Threading.Tasks.Task<string> GetVersionAsync()
        {
            return base.Channel.GetVersionAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IExaminationService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IExaminationService))
            {
                return new System.ServiceModel.EndpointAddress("http://kostasoft.tiera.ru:5392/N3ExaminationService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ExaminationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IExaminationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ExaminationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IExaminationService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IExaminationService,
        }
    }
}
