//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Trader
{

    public partial class Balance : XPBaseObject
    {
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>("ID", ref fID, value); }
        }
        decimal fVolume;
        /// <summary>
        /// количество бабок данной величины на балансе
        /// </summary>
        [DevExpress.Xpo.DisplayName(@"Объем")]
        public decimal Volume
        {
            get { return fVolume; }
            set { SetPropertyValue<decimal>("Volume", ref fVolume, value); }
        }
        string fCurrencyName;
        [Size(10)]
        [DevExpress.Xpo.DisplayName(@"имя валюты (кличка)")]
        public string CurrencyName
        {
            get { return fCurrencyName; }
            set { SetPropertyValue<string>("CurrencyName", ref fCurrencyName, value); }
        }
        DateTime fDate;
        [DevExpress.Xpo.DisplayName(@"Момент баланса")]
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>("Date", ref fDate, value); }
        }
        bool fIsFake;
        /// <summary>
        /// Признак того, что это баланс мнимого счета.
        /// </summary>
        [DevExpress.Xpo.DisplayName(@"Фейковый баланс")]
        public bool IsFake
        {
            get { return fIsFake; }
            set { SetPropertyValue<bool>("IsFake", ref fIsFake, value); }
        }
        Prediction fPrediction;
        /// <summary>
        /// Результат обработки данного предсказания
        /// </summary>
        [Association(@"BalanceReferencesPrediction")]
        [DevExpress.Xpo.DisplayName(@"По предсказанию")]
        public Prediction Prediction
        {
            get { return fPrediction; }
            set { SetPropertyValue<Prediction>("Prediction", ref fPrediction, value); }
        }
        decimal fPrice;
        [DevExpress.Xpo.DisplayName(@"Актуальная цена")]
        public decimal Price
        {
            get { return fPrice; }
            set { SetPropertyValue<decimal>("Price", ref fPrice, value); }
        }
    }

}
