//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Trader
{

    /// <summary>
    /// Свеча горела на столе, свеча горела
    /// </summary>
    public partial class Candle : XPBaseObject
    {
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>("ID", ref fID, value); }
        }
        Candle fPreviousCandle;
        [Indexed(Name = @"IDX_PreviewCandle")]
        [Association(@"CandleReferencesCandle")]
        [DevExpress.Xpo.DisplayName(@"Предыдущая свеча")]
        public Candle PreviousCandle
        {
            get { return fPreviousCandle; }
            set { SetPropertyValue<Candle>("PreviousCandle", ref fPreviousCandle, value); }
        }
        decimal fOpenPrice;
        [DevExpress.Xpo.DisplayName(@"Цена открытия")]
        public decimal OpenPrice
        {
            get { return fOpenPrice; }
            set { SetPropertyValue<decimal>("OpenPrice", ref fOpenPrice, value); }
        }
        decimal fClosePrice;
        [DevExpress.Xpo.DisplayName(@"Цена открытия")]
        public decimal ClosePrice
        {
            get { return fClosePrice; }
            set { SetPropertyValue<decimal>("ClosePrice", ref fClosePrice, value); }
        }
        decimal fMinPrice;
        [DevExpress.Xpo.DisplayName(@"Минимальная цена")]
        public decimal MinPrice
        {
            get { return fMinPrice; }
            set { SetPropertyValue<decimal>("MinPrice", ref fMinPrice, value); }
        }
        decimal fMaxPrice;
        [DevExpress.Xpo.DisplayName(@"Максимальная цена")]
        public decimal MaxPrice
        {
            get { return fMaxPrice; }
            set { SetPropertyValue<decimal>("MaxPrice", ref fMaxPrice, value); }
        }
        DateTime fStartDate;
        [DevExpress.Xpo.DisplayName(@"Дата начала")]
        public DateTime StartDate
        {
            get { return fStartDate; }
            set { SetPropertyValue<DateTime>("StartDate", ref fStartDate, value); }
        }
        DateTime fEndDate;
        [DevExpress.Xpo.DisplayName(@"Дата окончания")]
        public DateTime EndDate
        {
            get { return fEndDate; }
            set { SetPropertyValue<DateTime>("EndDate", ref fEndDate, value); }
        }
        Nsi_PairCurrency fCurrency;
        [Association(@"CandleXpoReferencesPairCurrency"), NoForeignKey]
        [DevExpress.Xpo.DisplayName(@"Валютная пара")]
        public Nsi_PairCurrency Currency
        {
            get { return fCurrency; }
            set { SetPropertyValue<Nsi_PairCurrency>("Currency", ref fCurrency, value); }
        }
        [Association(@"PredictionReferencesCandle")]
        public XPCollection<Prediction> Predictions { get { return GetCollection<Prediction>("Predictions"); } }
        [Association(@"CandleReferencesCandle"), Aggregated]
        public XPCollection<Candle> CandleCollection { get { return GetCollection<Candle>("CandleCollection"); } }
    }

}
