//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Trader
{

    public partial class Nsi_MacD : Nsi_Advice
    {
        short fExpPeriodLong;
        /// <summary>
        /// Период (глубина) длинной экспоненциальной скользящей средней
        /// </summary>
        [DevExpress.Xpo.DisplayName(@"Период экспоненциальной длинной")]
        public short ExpPeriodLong
        {
            get { return fExpPeriodLong; }
            set { SetPropertyValue<short>("ExpPeriodLong", ref fExpPeriodLong, value); }
        }
        short fExpPeriodShort;
        /// <summary>
        /// Период (глубина) короткой экспоненциальной скользящей средней
        /// </summary>
        [DevExpress.Xpo.DisplayName(@"Период экспоненциальной короткой")]
        public short ExpPeriodShort
        {
            get { return fExpPeriodShort; }
            set { SetPropertyValue<short>("ExpPeriodShort", ref fExpPeriodShort, value); }
        }
        short fSignalPeriod;
        /// <summary>
        /// Период (глубина) сигнальной SMA
        /// </summary>
        [DevExpress.Xpo.DisplayName(@"Период сигнальной SMA")]
        public short SignalPeriod
        {
            get { return fSignalPeriod; }
            set { SetPropertyValue<short>("SignalPeriod", ref fSignalPeriod, value); }
        }
    }

}
