//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Trader
{

    public partial class Nsi_StochRsi : Nsi_Advice
    {
        short fRsiDepth;
        [DevExpress.Xpo.DisplayName(@"Глубина Rsi")]
        public short RsiDepth
        {
            get { return fRsiDepth; }
            set { SetPropertyValue<short>("RsiDepth", ref fRsiDepth, value); }
        }
        short fStochDepth;
        [DevExpress.Xpo.DisplayName(@"Глубина расчета Стохастика")]
        public short StochDepth
        {
            get { return fStochDepth; }
            set { SetPropertyValue<short>("StochDepth", ref fStochDepth, value); }
        }
        short fMaPrima;
        [DevExpress.Xpo.DisplayName(@"Глубина первого сглаживания")]
        public short MaPrima
        {
            get { return fMaPrima; }
            set { SetPropertyValue<short>("MaPrima", ref fMaPrima, value); }
        }
        short fMaSecond;
        [DevExpress.Xpo.DisplayName(@"Второе сглаживание")]
        public short MaSecond
        {
            get { return fMaSecond; }
            set { SetPropertyValue<short>("MaSecond", ref fMaSecond, value); }
        }
    }

}
