//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Trader
{

    public partial class Nsi_Rsi : Nsi_Advice
    {
        short fDepth;
        [DevExpress.Xpo.DisplayName(@"Глубина расчета")]
        public short Depth
        {
            get { return fDepth; }
            set { SetPropertyValue<short>("Depth", ref fDepth, value); }
        }
        short fTopLevel;
        [DevExpress.Xpo.DisplayName(@"Уровень перекупленности")]
        public short TopLevel
        {
            get { return fTopLevel; }
            set { SetPropertyValue<short>("TopLevel", ref fTopLevel, value); }
        }
        short fButtomLevel;
        [DevExpress.Xpo.DisplayName(@"Уровень перепроданности")]
        public short ButtomLevel
        {
            get { return fButtomLevel; }
            set { SetPropertyValue<short>("ButtomLevel", ref fButtomLevel, value); }
        }
        short fSmaTrendLine;
        [DevExpress.Xpo.DisplayName(@"SMA Depth")]
        public short SmaTrendLine
        {
            get { return fSmaTrendLine; }
            set { SetPropertyValue<short>("SmaTrendLine", ref fSmaTrendLine, value); }
        }
    }

}
