//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Trader
{

    /// <summary>
    /// Биржа, справочник тех бирж, с которыми умеет работать ПО
    /// </summary>
    public partial class Nsi_Exchange : XPLiteObject
    {
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>("ID", ref fID, value); }
        }
        string fName;
        [DevExpress.Xpo.DisplayName(@"Наименование")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fApiAddress;
        [Size(255)]
        [DevExpress.Xpo.DisplayName(@"Адрес обращения Api")]
        public string ApiAddress
        {
            get { return fApiAddress; }
            set { SetPropertyValue<string>("ApiAddress", ref fApiAddress, value); }
        }
        string fApiKey;
        [DevExpress.Xpo.DisplayName(@"Приложенья ключ")]
        public string ApiKey
        {
            get { return fApiKey; }
            set { SetPropertyValue<string>("ApiKey", ref fApiKey, value); }
        }
        string fSecretKey;
        [DevExpress.Xpo.DisplayName(@"Секретный ключ")]
        public string SecretKey
        {
            get { return fSecretKey; }
            set { SetPropertyValue<string>("SecretKey", ref fSecretKey, value); }
        }
        [Association(@"Nsi_PairCurrencyReferencesNsi_Exchange")]
        public XPCollection<Nsi_PairCurrency> Nsi_PairCurrencys { get { return GetCollection<Nsi_PairCurrency>("Nsi_PairCurrencys"); } }
    }

}
