//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Trader
{

    public partial class Nsi_PairCurrency : XPLiteObject
    {
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>("ID", ref fID, value); }
        }
        string fName;
        [DevExpress.Xpo.DisplayName(@"Название пары")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        Nsi_Exchange fExchange;
        [Association(@"Nsi_PairCurrencyReferencesNsi_Exchange")]
        [DevExpress.Xpo.DisplayName(@"Биржа, которой принадлежит пара")]
        public Nsi_Exchange Exchange
        {
            get { return fExchange; }
            set { SetPropertyValue<Nsi_Exchange>("Exchange", ref fExchange, value); }
        }
        bool fActive;
        [DevExpress.Xpo.DisplayName(@"Активные")]
        public bool Active
        {
            get { return fActive; }
            set { SetPropertyValue<bool>("Active", ref fActive, value); }
        }
        [Association(@"CandleXpoReferencesPairCurrency")]
        public XPCollection<Candle> Candles { get { return GetCollection<Candle>("Candles"); } }
    }

}
