//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Duration { get; set; }
        public string Comment { get; set; }
        public int WeekId { get; set; }
        public int ProjectId { get; set; }
    
        public virtual Week Week { get; set; }
        public virtual Project Project { get; set; }
    }
}
