//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessAgent_Enterprise
    {
        public System.Guid ID { get; set; }
        public string DerivedType { get; set; }
        public System.Guid VersionID { get; set; }
        public System.Guid SessionID { get; set; }
        public Nullable<long> idSmo { get; set; }
        public string HospitalGroup { get; set; }
        public Nullable<System.Guid> EnterpriseID { get; set; }
        public Nullable<bool> IsDMSInsurer { get; set; }
        public Nullable<bool> IsOMSInsurer { get; set; }
        public bool IsInsurer { get; set; }
        public bool IsEmployer { get; set; }
        public Nullable<bool> IsOU { get; set; }
        public Nullable<bool> IsDOU { get; set; }
        public bool IsDirection { get; set; }
        public bool IsForTFG { get; set; }
        public bool IsOutpatientClinic { get; set; }
        public bool IsInpatientClinic { get; set; }
        public bool IsLocalInsurer { get; set; }
        public string Telephone { get; set; }
        public string NameForTempDisability { get; set; }
        public string RegistryNumber { get; set; }
        public Nullable<long> OuterAgentDirectF66_1 { get; set; }
        public Nullable<long> WhereDischargedF66_1 { get; set; }
        public Nullable<int> CodeForNetrika { get; set; }
        public Nullable<long> LPUType { get; set; }
        public Nullable<System.Guid> AdmRegionForNetrikaID { get; set; }
        public Nullable<System.Guid> DirectionTypeID { get; set; }
        public Nullable<bool> IsPND { get; set; }
        public Nullable<bool> IsPB { get; set; }
        public Nullable<bool> IsAttach { get; set; }
        public bool OrganisationOfReceipt { get; set; }
        public Nullable<bool> IsCourt { get; set; }
        public Nullable<bool> IsSanatorium { get; set; }
        public Nullable<bool> LateRehabilitation { get; set; }
        public bool IsExternalMO { get; set; }
        public bool IsFor57Form { get; set; }
        public Nullable<bool> IsDoverAgent { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
    }
}
