//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurEnterprise
    {
        public System.Guid ID { get; set; }
        public string DerivedType { get; set; }
        public System.Guid VersionID { get; set; }
        public System.Guid SessionID { get; set; }
        public Nullable<bool> GiveTempDisability { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsTempDisabilityByDefault { get; set; }
        public Nullable<System.Guid> EnterpriseID { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
    }
}
