// This file was auto-generated by ML.NET Model Builder. 

using System;
using MLConsoleML.Model;

namespace MLConsoleML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                VectorSMA = @"",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Advice with predicted Advice from sample data...\n\n");
            Console.WriteLine($"VectorSMA: {sampleData.VectorSMA}");
            Console.WriteLine($"\n\nPredicted Advice: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
